# Global configuration settings for the Andromeda3 project

# The device to run the models on. Options: "cuda", "cpu"
device: "cuda"

# A random seed for reproducibility across runs
random_seed: 42

# Environment dimensions
observation_shape: [237] # Example: 1D observation space
action_dim: 8
reward_dim: 1

# --- Logging Configuration ---
logging:
  # Weights & Biases project name
  project_name: "Andromeda2"

  # Optional: W&B entity (username or team name)
  # entity: "your_entity"